name: lunchPicker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - run: yarn
    - run: yarn run test
    - run: yarn run deploy-firebase
